<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::talbe('products')->insert([
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    		[
    			'brand_id' => '',
    			'category_id' => '',
    			'name' => '',
    			'description' => '',
    			'price' => '',
    			'quantity' => '',
    			'image' => 'img/products/',
    		],
    	]);
}
}
