<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('products')->insert([
    		[
    			'brand_id' => '2',
    			'category_id' => '3',
    			'name' => 'Artel Boro 12',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '350',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/air_artel.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '6',
    			'category_id' => '3',
    			'name' => 'Gree Fairy 12',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '385',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/air_gree.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '8',
    			'category_id' => '3',
    			'name' => 'LG Lomo 12',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '395',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/air_lg.jpg',
    			'discount' => null,
    		],[
    			'brand_id' => '2',
    			'category_id' => '6',
    			'name' => 'Container Vacuum Cleaner VCC0120-BL',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '50',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/cleaner_artel.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '8',
    			'category_id' => '6',
    			'name' => 'LG CordZero A9',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '150',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/cleaner_lg.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '11',
    			'category_id' => '6',
    			'name' => 'VC18M3110VB Canister Bagless Vacuum cleaner, 1800 W',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '120',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/cleaner_samsung.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '3',
    			'category_id' => '8',
    			'name' => 'Gas Stove Bosch T6311T6 Inox',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '350',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/gas_bosch.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '5',
    			'category_id' => '8',
    			'name' => 'Gas Stove Goodwell GWC-6401B',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '430',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/gas_goodwell.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '8',
    			'category_id' => '8',
    			'name' => 'Gas Stove LG 800 Series Slide-in Range HGIP0556UC',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '285',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/gas_lg.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '2',
    			'category_id' => '11',
    			'name' => 'Microwave Artel MD-4218E',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '60',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/mic_artel.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '3',
    			'category_id' => '11',
    			'name' => 'Microwave Bosch MGF-20210X',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '100',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/mic_bosch.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '8',
    			'category_id' => '11',
    			'name' => 'Microwave LG NN-GT264M',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '120',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/mic_lg.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '4',
    			'category_id' => '2',
    			'name' => 'Gigabyte Aorus New Case',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '45',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/pc_gigabyte.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '9',
    			'category_id' => '2',
    			'name' => 'MSI Dragon 100X',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '80',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/pc_msi.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '10',
    			'category_id' => '2',
    			'name' => 'Razer LIAN LI O11 DYNAMIC',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '70',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/pc_razer.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '1',
    			'category_id' => '1',
    			'name' => 'Apple Iphone 12 Pro Max 128gb Black',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '1100',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/phone_apple.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '12',
    			'category_id' => '1',
    			'name' => 'Xiaomi Mi10 Pro 128gb',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '560',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/phone_mi.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '11',
    			'category_id' => '1',
    			'name' => 'Samsung S20 Ultra Plus 256gb Love Purple',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '980',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/phone_samsung.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '3',
    			'category_id' => '9',
    			'name' => 'Refrigerator Bosch RCNK 400E20ZX',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '750',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/ref_bosch.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '5',
    			'category_id' => '9',
    			'name' => 'Refrigerator Goodwell GRF S490XL/D1',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '820',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/ref_goodwell.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '7',
    			'category_id' => '9',
    			'name' => 'Refrigerator Indesit HD-341FN',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '310',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/ref_indesit.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '2',
    			'category_id' => '12',
    			'name' => 'Teapot Artel KE-8815',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '15',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/tea_artel.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '3',
    			'category_id' => '12',
    			'name' => 'Teapot Bosch TWK 7804',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '65',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/tea_bosch.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '12',
    			'category_id' => '12',
    			'name' => 'Teapot Xiaomi Smart Kettle Bluetoogh',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '45',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/tea_mi.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '2',
    			'category_id' => '4',
    			'name' => 'Artel 55AU20H UHD Smart TV',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '650',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/tv_artel.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '8',
    			'category_id' => '4',
    			'name' => 'TV LG OLED65CXRLA 4K',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '3500',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/tv_lg.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '11',
    			'category_id' => '4',
    			'name' => 'Samsung UE65NU7090U 4K UHD Smart TV',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '1150',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/tv_samsung.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '2',
    			'category_id' => '7',
    			'name' => 'Washing Machine Artel 60C101',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '280',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/wash_artel.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '3',
    			'category_id' => '7',
    			'name' => 'Washing Machine Bosch Serie 4 WGA242X0ME',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '420',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/wash_bosch.jpg',
    			'discount' => null,
    		],
    		[
    			'brand_id' => '11',
    			'category_id' => '7',
    			'name' => 'Washing Machine Samsung WW70R62LATX AddWash',
    			'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam doloremque maiores vitae id minima, perspiciatis maxime omnis a deleniti accusantium earum facilis, quisquam cum at, facere sunt magni quas velit.',
    			'price' => '680',
    			'quantity' => rand(1,10),
    			'image' => 'img/products/wash_samsung.jpg',
    			'discount' => null,
    		],
    	]);
}
}
